### ISSUE TITLE
Behavior by the difference in version of Chrome

### ISSUE THREAD

**Issue by ka0123** [harisenbon/autokana#12]
In version upgrade of Chrome
We have confirmed the phenomenon that the Japanese syllabary auto-input can not be performed.
jquery.autokana.js

Ver which has been confirmed is Chrome beta version Canaria (ver: 75.0.3759.0/64bit)

There is no problem with the current ver: 73.0.3683.103, but it is very likely to occur in the future.

Is it possible to request a response to this?
Or do you plan to respond in the future?

**Comment by harisenbon** [comment]
What was the error that was displayed in v75?
(日本語でもOK）

**Comment by ka0123** [comment]
日本語OKの旨、ありがとうとざいます！

かな入力が自動挿入されなくなったのみで
エラーは何も表示されませんでした。
デベロッパーツール(Console)上でもエラー表記は何もありませんでした。
Chrome Canaryの拡張機能をすべてOFFし、
アンインストールの後に再インストールでも改善せず。



違いはというと
入力方法がベータ版の75.0.3759.0付近に切り替わったタイミングで
変換前のテキスト入力時の表示が切り替わっているところのみです。

OS Windows7

Chrome
　https://gyazo.com/29476a715b3bb23b605149fdc867613d
Chrome Canary ベータ版
　https://gyazo.com/f994b658d724f98b350cd2913546b150

------
以上が昨日までに判明していた情報で
本日1点新たにわかった点があり情報共有させていただきます。

インストールされているGoogleIMEを
MicrosoftIMEに切り替えると現象が解消することが確認できました。

上記入力方法が異なる点などを加味すると
GoogleIME側の問題のような気がするので
一旦こちらの問い合わせは完了とさせていただけたらと思います。
お手数おかけしました。
そして、ご対応ありがとうございました。

**Comment by harisenbon** [comment]
ご親切なご説明をありがとうございます。
GoogleIMEの対応を確認いたします。

そろそろAutoKanaをアップデートしたいと思っていましたのでいいきっかけになります。
