### ISSUE TITLE
”*”を入力するとエラーが発生

### ISSUE THREAD

**Issue by taizdo1024** [harisenbon/autokana#4]
"*"を入力するとjquery.autoKana.jsの134行目でエラーが発生します。
chromeの場合：
```
Uncaught SyntaxError: Invalid regular expression: /*/: Nothing to repeat
jquery.autoKana.js: 134
```
エラーとなる個所を下記のように修正すると回避できました。
```
if (new_input.match(ignoreString.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&"))) {
```

**Comment by danielheffernan** [comment]
This is because `match` created a `RegExp` from the string input.

A nice way to fix this is to remove the [`match`](https://github.com/harisenbon/autokana/blob/master/jquery.autoKana.js#L134) call and replace it with, for example:

`if (new_input.indexOf(ignoreString) != -1) {`

**Comment by taizdo1024** [comment]
返信ありがとうございます。
indexOf()を使って回避してみます。
