### ISSUE TITLE
Question about this library's roadmap

### ISSUE THREAD

**Issue by ohbarye** [harisenbon/autokana#7]
Hello maintainers. Do you have any plan to take an action for this library in the future?

e.g.

1. Publish this library in https://www.npmjs.com/
2. Remove dependency on jQuery

**Comment by harisenbon** [comment]
I'm happy to make updates / fixes, but currently I don't have any plans to port the code to another JS framework. One person has made a fork for angular, and you can find that here:
https://github.com/verybestjp/autokana

I will publish the library to npmjs.com now.

I'm curious, by "removing dependency on jQuery" do you mean it should use Vanilla JS?

**Comment by ohbarye** [comment]
Thanks for your quick answer, understood!

> I'm curious, by "removing dependency on jQuery" do you mean it should use Vanilla JS?

Correct. That's what I imagined.
To be precise, I was considering to implement the autokana feature in my React app (as you guess, without jQuery dependency), then my concern was whether I should write it from scratch or fork this repo and tweak somehow or not.

**Comment by harisenbon** [comment]
I would love to build it as a non-jquery library, but even if I did, you would probably need to do some tweaking on it to get it to place nice with React. (I haven't used react, so not sure what that would entail).

It might be best to fork the repo, and make a react version. I can then link your react version in the readme of the main repo.

**Comment by ohbarye** [comment]
Got it. Okay then I'll try to build a React version somehow by myself.

I appreciate your concern!

**Comment by ohbarye** [comment]
📝 Just a note: After a long long time, I finally published my own library written in React. 
https://github.com/ohbarye/react-kana-provider
